// Writes the minimized config out as a standalone Rspack config file.
//
// Rspeedy generates the config here, once. What it writes has no Rsbuild or
// Rspeedy left in it: two entries in two layers, the module rules, and the two
// loaders from `@lynx-js/react-webpack-plugin`, which are the ingredient the
// bug needs. `rspack build -c rspack.config.mjs` then reproduces on its own.
import { writeFileSync } from 'node:fs'
import path from 'node:path'

import { pluginReactLynx } from '@lynx-js/react-rsbuild-plugin'
import { createRspeedy } from '@lynx-js/rspeedy'

const cwd = import.meta.dirname

const rspeedy = await createRspeedy({
  cwd,
  rspeedyConfig: {
    mode: 'production',
    environments: { lynx: {} },
    source: { entry: { main: './src/plain.js' } },
    output: { distPath: { root: 'emit-out' } },
    plugins: [pluginReactLynx()],
  },
})

const [config] = await rspeedy.initConfigs()

// Everything Lynx contributes as an Rspack *plugin* is dropped; only the
// loaders are kept. `SourceMapDevToolPlugin` comes from Rspack itself and is
// reconstructed in the emitted file, because without it the build is
// reproducible.
const sourceMapOptions = (config.plugins ?? [])
  .filter((p) => /^SourceMap/.test(p?.constructor?.name ?? ''))
  .map((p) => p.options ?? p._options ?? {})
delete config.plugins
config.output = {
  ...config.output,
  chunkLoading: false,
  workerChunkLoading: false,
  path: path.join(cwd, 'standalone-dist'),
}
config.entry = Object.fromEntries(
  Object.entries(config.entry).map(([name, value]) => [
    name,
    { ...value, chunkLoading: false, filename: `${name}.js` },
  ]),
)
config.optimization = {
  ...config.optimization,
  concatenateModules: false,
  minimize: false,
  minimizer: undefined,
  splitChunks: undefined,
}
delete config.resolve
delete config.devtool
delete config.infrastructureLogging
delete config.watchOptions
delete config.name

function serialize(value, indent = '  ') {
  if (value === undefined) return 'undefined'
  if (value === null) return 'null'
  if (value instanceof RegExp) return String(value)
  if (typeof value === 'function') {
    throw new Error(`cannot serialize a function: ${value.name}`)
  }
  if (typeof value !== 'object') return JSON.stringify(value)
  const next = indent + '  '
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]'
    return `[\n${
      value.map((v) => next + serialize(v, next)).join(',\n')
    }\n${indent}]`
  }
  const entries = Object.entries(value).filter(([, v]) => v !== undefined)
  if (entries.length === 0) return '{}'
  return `{\n${
    entries
      .map(([k, v]) => `${next}${JSON.stringify(k)}: ${serialize(v, next)}`)
      .join(',\n')
  }\n${indent}}`
}

const probe = `
import { createHash } from 'node:crypto'
import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import { rspack } from '@rspack/core'

// Records what Rspack computes per module, so a pair of builds can be compared
// on the module hash rather than on the emitted bytes.
class Probe {
  apply(compiler) {
    compiler.hooks.compilation.tap('Probe', (compilation) => {
      compilation.hooks.processAssets.tap(
        { name: 'Probe', stage: rspack.Compilation.PROCESS_ASSETS_STAGE_REPORT },
        () => {
          const out = []
          for (const chunk of compilation.chunks) {
            const runtime = typeof chunk.runtime === 'string'
              ? chunk.runtime
              : [...chunk.runtime][0]
            const modules = []
            for (const m of compilation.chunkGraph.getChunkModules(chunk)) {
              let codegen = '<err>'
              let moduleHash = '<err>'
              try {
                const src = compilation.codeGenerationResults
                  .get(m, runtime).sources.get('javascript')
                codegen = createHash('sha1').update(src ? src.source() : '')
                  .digest('hex')
              } catch {}
              try {
                moduleHash = compilation.chunkGraph.getModuleHash(m, runtime)
              } catch {}
              modules.push({ id: m.identifier(), moduleHash, codegen })
            }
            modules.sort((a, b) => a.id.localeCompare(b.id))
            out.push({ name: chunk.name, hash: chunk.hash, modules })
          }
          out.sort((a, b) => String(a.name).localeCompare(String(b.name)))
          const into = process.env.OUT ?? 'standalone-dist'
          mkdirSync(into, { recursive: true })
          writeFileSync(
            path.join(into, 'probe.json'),
            JSON.stringify(out, null, 2),
          )
        },
      )
    })
  }
}
`

writeFileSync(
  path.join(cwd, 'rspack.config.mjs'),
  `// Generated by emit-config.mjs. Plain Rspack: no Rsbuild, no Rspeedy.
${probe}
const SOURCE_MAP_OPTIONS = ${serialize(sourceMapOptions)}

const config = ${serialize(config)}

config.output.path = process.env.OUT
  ? path.resolve(process.env.OUT)
  : config.output.path
config.plugins = [
  ...SOURCE_MAP_OPTIONS.map((options) => new rspack.SourceMapDevToolPlugin(options)),
  new Probe(),
]

export default config
`,
)

console.log('wrote rspack.config.mjs')
