// Generated by emit-config.mjs. Plain Rspack: no Rsbuild, no Rspeedy.

import { createHash } from 'node:crypto'
import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import { rspack } from '@rspack/core'

// Records what Rspack computes per module, so a pair of builds can be compared
// on the module hash rather than on the emitted bytes.
class Probe {
  apply(compiler) {
    compiler.hooks.compilation.tap('Probe', (compilation) => {
      compilation.hooks.processAssets.tap(
        { name: 'Probe', stage: rspack.Compilation.PROCESS_ASSETS_STAGE_REPORT },
        () => {
          const out = []
          for (const chunk of compilation.chunks) {
            const runtime = typeof chunk.runtime === 'string'
              ? chunk.runtime
              : [...chunk.runtime][0]
            const modules = []
            for (const m of compilation.chunkGraph.getChunkModules(chunk)) {
              let codegen = '<err>'
              let moduleHash = '<err>'
              try {
                const src = compilation.codeGenerationResults
                  .get(m, runtime).sources.get('javascript')
                codegen = createHash('sha1').update(src ? src.source() : '')
                  .digest('hex')
              } catch {}
              try {
                moduleHash = compilation.chunkGraph.getModuleHash(m, runtime)
              } catch {}
              modules.push({ id: m.identifier(), moduleHash, codegen })
            }
            modules.sort((a, b) => a.id.localeCompare(b.id))
            out.push({ name: chunk.name, hash: chunk.hash, modules })
          }
          out.sort((a, b) => String(a.name).localeCompare(String(b.name)))
          const into = process.env.OUT ?? 'standalone-dist'
          mkdirSync(into, { recursive: true })
          writeFileSync(
            path.join(into, 'probe.json'),
            JSON.stringify(out, null, 2),
          )
        },
      )
    })
  }
}

const SOURCE_MAP_OPTIONS = [
    {},
    {
      "filename": "[file].map[query]",
      "moduleFilenameTemplate": "file://[absolute-resource-path]",
      "fallbackModuleFilenameTemplate": "file://[absolute-resource-path]?[hash]",
      "module": true,
      "columns": true,
      "noSources": false,
      "publicPath": "http://192.168.1.174:3000/",
      "debugIds": false
    }
  ]

const config = {
    "target": [
      "es2017"
    ],
    "context": "/Users/bytedance/projects/rspeedy-minify-repro",
    "mode": "production",
    "experiments": {
      "sourceImport": true
    },
    "output": {
      "devtoolModuleFilenameTemplate": "[relative-resource-path]",
      "devtoolFallbackModuleFilenameTemplate": "[relative-resource-path]?[hash]",
      "path": "/Users/bytedance/projects/rspeedy-minify-repro/standalone-dist",
      "filename": "static/js/[name].[contenthash:10].js",
      "chunkFilename": "static/js/async/[name].[contenthash:10].js",
      "publicPath": "http://192.168.1.174:3000/",
      "environment": {
        "const": false
      },
      "assetModuleFilename": "static/assets/[name].[contenthash:10][ext]",
      "webassemblyModuleFilename": "static/wasm/[contenthash:10].module.wasm",
      "chunkLoading": false,
      "chunkFormat": "commonjs",
      "iife": false,
      "workerChunkLoading": false
    },
    "module": {
      "parser": {
        "javascript": {
          "typeReexportsPresence": "tolerant"
        }
      },
      "rules": [
        {
          "test": /\.m?js/,
          "resolve": {
            "fullySpecified": false
          }
        },
        {
          "test": /\.css$/,
          "dependency": {
            "not": "url"
          },
          "oneOf": [
            {
              "with": {
                "type": "text"
              },
              "type": "asset/source"
            },
            {
              "resourceQuery": /[?&]url(?:&|=|$)/,
              "use": [
                {
                  "loader": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@rsbuild/core/dist/cssUrlLoader.mjs",
                  "options": {
                    "filename": ".rspeedy/[name]/[name].css",
                    "modules": {
                      "auto": true,
                      "namedExport": false,
                      "exportGlobals": false,
                      "exportLocalsConvention": "camelCase",
                      "localIdentName": "[local]-[hash:base64:6]"
                    }
                  }
                },
                {
                  "loader": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@rsbuild/core/compiled/css-loader/index.js",
                  "options": {
                    "modules": false,
                    "sourceMap": true,
                    "exportType": "string",
                    "importLoaders": 1
                  }
                },
                {
                  "loader": "builtin:lightningcss-loader",
                  "options": {
                    "targets": [
                      "chrome >= 107",
                      "edge >= 107",
                      "firefox >= 104",
                      "safari >= 16"
                    ],
                    "errorRecovery": true,
                    "minify": true
                  }
                }
              ],
              "resolve": {
                "preferRelative": true
              }
            },
            {
              "resourceQuery": /[?&]inline(?:&|=|$)/,
              "sideEffects": true,
              "use": [
                {
                  "loader": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@rsbuild/core/compiled/css-loader/index.js",
                  "options": {
                    "modules": false,
                    "sourceMap": true,
                    "exportType": "string",
                    "importLoaders": 1
                  }
                }
              ],
              "resolve": {
                "preferRelative": true
              }
            },
            {
              "type": "asset/source",
              "resourceQuery": /[?&]raw(?:&|=|$)/
            },
            {
              "sideEffects": true,
              "issuerLayer": "react:background",
              "use": [
                {
                  "loader": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/css-extract-webpack-plugin/lib/rspack-loader.js"
                },
                {
                  "loader": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@rsbuild/core/compiled/css-loader/index.js",
                  "options": {
                    "modules": {
                      "auto": true,
                      "namedExport": false,
                      "exportGlobals": false,
                      "exportLocalsConvention": "camelCase",
                      "localIdentName": "[local]-[hash:base64:6]"
                    },
                    "sourceMap": true,
                    "importLoaders": 1
                  }
                }
              ],
              "resolve": {
                "preferRelative": true
              }
            }
          ]
        },
        {
          "test": /\.(?:js|jsx|mjs|cjs|ts|tsx|mts|cts)$/,
          "dependency": {
            "not": "url"
          },
          "include": [
            {
              "not": /[\\/]node_modules[\\/]/
            },
            /\.(?:ts|tsx|jsx|mts|cts)$/,
            "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react",
            /\.(?:js|jsx|mjs|cjs|ts|tsx|mts|cts)$/
          ],
          "oneOf": [
            {
              "resourceQuery": /[?&]worker(?:&|=|$)/,
              "type": "javascript/auto",
              "use": [
                {
                  "loader": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@rsbuild/core/dist/workerLoader.mjs"
                }
              ]
            },
            {
              "with": {
                "type": "text"
              },
              "type": "asset/source"
            },
            {
              "resourceQuery": /[?&]raw(?:&|=|$)/,
              "type": "asset/source"
            },
            {
              "type": "javascript/auto",
              "oneOf": [
                {
                  "issuerLayer": "react:background",
                  "type": "javascript/auto",
                  "use": [
                    {
                      "loader": "builtin:swc-loader",
                      "options": {
                        "detectSyntax": "auto",
                        "jsc": {
                          "externalHelpers": true,
                          "parser": {
                            "decorators": true,
                            "syntax": "typescript",
                            "tsx": false
                          },
                          "experimental": {
                            "cacheRoot": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/.cache/.swc",
                            "keepImportAttributes": true
                          },
                          "output": {
                            "charset": "utf8"
                          },
                          "transform": {
                            "legacyDecorator": false,
                            "decoratorVersion": "2023-11",
                            "useDefineForClassFields": false,
                            "optimizer": {
                              "simplify": true
                            }
                          }
                        },
                        "isModule": "unknown",
                        "env": {
                          "targets": {
                            "chrome": "120"
                          },
                          "include": [
                            "transform-block-scoping",
                            "transform-async-generator-functions",
                            "transform-dotall-regex",
                            "transform-named-capturing-groups-regex",
                            "transform-object-rest-spread",
                            "transform-unicode-property-regex",
                            "transform-json-strings",
                            "transform-optional-catch-binding",
                            "transform-nullish-coalescing-operator",
                            "transform-optional-chaining",
                            "transform-export-namespace-from",
                            "transform-logical-assignment-operators",
                            "transform-numeric-separator",
                            "transform-class-properties",
                            "transform-class-static-block",
                            "transform-private-methods",
                            "transform-private-property-in-object"
                          ]
                        },
                        "collectTypeScriptInfo": {
                          "typeExports": true,
                          "exportedEnum": true
                        }
                      }
                    },
                    {
                      "loader": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react-webpack-plugin/lib/loaders/background.js",
                      "options": {
                        "enableRemoveCSSScope": true,
                        "isDynamicComponent": false,
                        "inlineSourcesContent": true,
                        "engineVersion": "3.2",
                        "experimental_transformBuiltinAttributeNames": false,
                        "experimental_useElementTemplate": false
                      }
                    }
                  ]
                },
                {
                  "issuerLayer": "react:main-thread",
                  "type": "javascript/auto",
                  "use": [
                    {
                      "loader": "builtin:swc-loader",
                      "options": {
                        "detectSyntax": "auto",
                        "jsc": {
                          "externalHelpers": true,
                          "parser": {
                            "decorators": true,
                            "syntax": "typescript",
                            "tsx": false
                          },
                          "experimental": {
                            "cacheRoot": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/.cache/.swc",
                            "keepImportAttributes": true
                          },
                          "output": {
                            "charset": "utf8"
                          },
                          "transform": {
                            "legacyDecorator": false,
                            "decoratorVersion": "2023-11",
                            "useDefineForClassFields": false,
                            "optimizer": {
                              "simplify": true
                            }
                          }
                        },
                        "isModule": "unknown",
                        "env": {
                          "targets": {
                            "chrome": "120"
                          },
                          "include": [
                            "transform-block-scoping",
                            "transform-nullish-coalescing-operator",
                            "transform-optional-chaining",
                            "transform-export-namespace-from",
                            "transform-logical-assignment-operators",
                            "transform-numeric-separator",
                            "transform-class-properties",
                            "transform-class-static-block",
                            "transform-private-methods",
                            "transform-private-property-in-object"
                          ]
                        },
                        "collectTypeScriptInfo": {
                          "typeExports": true,
                          "exportedEnum": true
                        }
                      }
                    },
                    {
                      "loader": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react-webpack-plugin/lib/loaders/main-thread.js",
                      "options": {
                        "enableRemoveCSSScope": true,
                        "isDynamicComponent": false,
                        "inlineSourcesContent": true,
                        "engineVersion": "3.2",
                        "experimental_transformBuiltinAttributeNames": false,
                        "experimental_useElementTemplate": false,
                        "enableUiSourceMap": false
                      }
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "mimetype": {
            "or": [
              "text/javascript",
              "application/javascript"
            ]
          },
          "use": [
            {
              "loader": "builtin:swc-loader",
              "options": {
                "detectSyntax": "auto",
                "jsc": {
                  "externalHelpers": true,
                  "parser": {
                    "decorators": true,
                    "syntax": "typescript",
                    "tsx": false
                  },
                  "experimental": {
                    "cacheRoot": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/.cache/.swc",
                    "keepImportAttributes": true
                  },
                  "output": {
                    "charset": "utf8"
                  },
                  "transform": {
                    "legacyDecorator": false,
                    "decoratorVersion": "2023-11",
                    "useDefineForClassFields": false,
                    "optimizer": {
                      "simplify": true
                    }
                  }
                },
                "isModule": "unknown",
                "env": {
                  "targets": {
                    "chrome": "120"
                  },
                  "include": [
                    "transform-block-scoping",
                    "transform-async-generator-functions",
                    "transform-dotall-regex",
                    "transform-named-capturing-groups-regex",
                    "transform-object-rest-spread",
                    "transform-unicode-property-regex",
                    "transform-json-strings",
                    "transform-optional-catch-binding",
                    "transform-nullish-coalescing-operator",
                    "transform-optional-chaining",
                    "transform-export-namespace-from",
                    "transform-logical-assignment-operators",
                    "transform-numeric-separator",
                    "transform-class-properties",
                    "transform-class-static-block",
                    "transform-private-methods",
                    "transform-private-property-in-object"
                  ]
                },
                "collectTypeScriptInfo": {
                  "typeExports": true,
                  "exportedEnum": true
                }
              }
            }
          ],
          "resolve": {
            "fullySpecified": false
          }
        },
        {
          "test": /\.json$/,
          "type": "json",
          "generator": {
            "JSONParse": false
          },
          "issuerLayer": "react:main-thread"
        },
        {
          "test": /\.(?:png|jpg|jpeg|pjpeg|pjp|gif|bmp|webp|ico|apng|avif|tif|tiff|jfif|cur|jxl)$/i,
          "oneOf": [
            {
              "type": "asset/resource",
              "resourceQuery": /[?&]url(?:&|=|$)/,
              "generator": {
                "filename": "static/image/[name].[contenthash:10][ext]"
              }
            },
            {
              "type": "asset/inline",
              "resourceQuery": /[?&]inline(?:&|=|$)/
            },
            {
              "type": "asset/source",
              "with": {
                "type": "text"
              }
            },
            {
              "type": "asset/source",
              "resourceQuery": /[?&]raw(?:&|=|$)/
            },
            {
              "type": "asset",
              "parser": {
                "dataUrlCondition": {
                  "maxSize": 2048
                }
              },
              "generator": {
                "filename": "static/image/[name].[contenthash:10][ext]"
              }
            }
          ]
        },
        {
          "test": /\.svg$/i,
          "oneOf": [
            {
              "type": "asset/resource",
              "resourceQuery": /[?&]url(?:&|=|$)/,
              "generator": {
                "filename": "static/svg/[name].[contenthash:10].svg"
              }
            },
            {
              "type": "asset/inline",
              "resourceQuery": /[?&]inline(?:&|=|$)/
            },
            {
              "type": "asset/source",
              "with": {
                "type": "text"
              }
            },
            {
              "type": "asset/source",
              "resourceQuery": /[?&]raw(?:&|=|$)/
            },
            {
              "type": "asset",
              "parser": {
                "dataUrlCondition": {
                  "maxSize": 2048
                }
              },
              "generator": {
                "filename": "static/svg/[name].[contenthash:10].svg"
              }
            }
          ]
        },
        {
          "test": /\.(?:mp4|webm|ogg|mov|mp3|wav|flac|aac|m4a|opus|vtt)$/i,
          "oneOf": [
            {
              "type": "asset/resource",
              "resourceQuery": /[?&]url(?:&|=|$)/,
              "generator": {
                "filename": "static/media/[name].[contenthash:10][ext]"
              }
            },
            {
              "type": "asset/inline",
              "resourceQuery": /[?&]inline(?:&|=|$)/
            },
            {
              "type": "asset/source",
              "with": {
                "type": "text"
              }
            },
            {
              "type": "asset/source",
              "resourceQuery": /[?&]raw(?:&|=|$)/
            },
            {
              "type": "asset",
              "parser": {
                "dataUrlCondition": {
                  "maxSize": 2048
                }
              },
              "generator": {
                "filename": "static/media/[name].[contenthash:10][ext]"
              }
            }
          ]
        },
        {
          "test": /\.(?:woff|woff2|eot|ttf|otf|ttc)$/i,
          "oneOf": [
            {
              "type": "asset/resource",
              "resourceQuery": /[?&]url(?:&|=|$)/,
              "generator": {
                "filename": "static/font/[name].[contenthash:10][ext]"
              }
            },
            {
              "type": "asset/inline",
              "resourceQuery": /[?&]inline(?:&|=|$)/
            },
            {
              "type": "asset/source",
              "with": {
                "type": "text"
              }
            },
            {
              "type": "asset/source",
              "resourceQuery": /[?&]raw(?:&|=|$)/
            },
            {
              "type": "asset",
              "parser": {
                "dataUrlCondition": {
                  "maxSize": 2048
                }
              },
              "generator": {
                "filename": "static/font/[name].[contenthash:10][ext]"
              }
            }
          ]
        },
        {
          "test": /\.(?:webmanifest|pdf|txt)$/i,
          "oneOf": [
            {
              "type": "asset/resource",
              "resourceQuery": /[?&]url(?:&|=|$)/,
              "generator": {
                "filename": "static/assets/[name].[contenthash:10][ext]"
              }
            },
            {
              "type": "asset/inline",
              "resourceQuery": /[?&]inline(?:&|=|$)/
            },
            {
              "type": "asset/source",
              "with": {
                "type": "text"
              }
            },
            {
              "type": "asset/source",
              "resourceQuery": /[?&]raw(?:&|=|$)/
            },
            {
              "type": "asset",
              "parser": {
                "dataUrlCondition": {
                  "maxSize": 2048
                }
              },
              "generator": {
                "filename": "static/assets/[name].[contenthash:10][ext]"
              }
            }
          ]
        },
        {
          "test": /\.json$/i,
          "oneOf": [
            {
              "type": "asset/source",
              "with": {
                "type": "text"
              }
            },
            {
              "type": "asset/source",
              "resourceQuery": /[?&]raw(?:&|=|$)/
            }
          ]
        },
        {
          "test": /\.wasm$/,
          "dependency": "url",
          "type": "asset/resource",
          "generator": {
            "filename": "static/wasm/[contenthash:10].module.wasm"
          }
        },
        {
          "issuerLayer": "react:main-thread",
          "resolve": {
            "alias": {
              "react/jsx-runtime": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/lepus/jsx-runtime/index.js",
              "react/jsx-dev-runtime": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/lepus/jsx-runtime/index.js",
              "@lynx-js/react/jsx-runtime": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/lepus/jsx-runtime/index.js",
              "@lynx-js/react/jsx-dev-runtime": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/lepus/jsx-runtime/index.js",
              "@lynx-js/react/lepus$": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/lepus/index.js",
              "@lynx-js/react/lepus/jsx-runtime": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/lepus/jsx-runtime/index.js",
              "@lynx-js/react/lepus/jsx-dev-runtime": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/lepus/jsx-runtime/index.js",
              "preact/hooks": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/lib/core/hooks/mainThread.js",
              "@lynx-js/react/hooks": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/lib/core/hooks/mainThread.js",
              "@lynx-js/react/lepus/hooks": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/lib/core/hooks/mainThread.js",
              "@lynx-js/react-signals$": "@lynx-js/react-signals/lepus"
            }
          }
        },
        {
          "issuerLayer": "react:background",
          "resolve": {
            "alias": {
              "react/jsx-runtime": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/jsx-runtime/index.js",
              "react/jsx-dev-runtime": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/jsx-dev-runtime/index.js",
              "@lynx-js/react/jsx-runtime": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/jsx-runtime/index.js",
              "@lynx-js/react/jsx-dev-runtime": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/jsx-dev-runtime/index.js",
              "@lynx-js/react/lepus$": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/lib/index.js",
              "preact/hooks": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/preact/hooks/dist/hooks.mjs",
              "@lynx-js/react/hooks": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react/runtime/lib/core/hooks/react.js"
            }
          }
        },
        {
          "type": "javascript/auto",
          "test": /\.(?:js|jsx|mjs|cjs|ts|tsx|mts|cts)$/,
          "parser": {
            "overrideStrict": "strict"
          }
        },
        {
          "test": /\.css$/,
          "sideEffects": true,
          "issuerLayer": "react:main-thread",
          "dependency": {
            "not": "url"
          },
          "use": [
            {
              "loader": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react-rsbuild-plugin/dist/loaders/ignore-css-loader"
            },
            {
              "loader": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@rsbuild/core/compiled/css-loader/index.js",
              "options": {
                "modules": {
                  "auto": true,
                  "namedExport": false,
                  "exportGlobals": false,
                  "exportLocalsConvention": "camelCase",
                  "localIdentName": "[local]-[hash:base64:6]",
                  "exportOnlyLocals": true
                },
                "sourceMap": true,
                "importLoaders": 1
              }
            }
          ]
        },
        {
          "issuerLayer": "react:main-thread",
          "resolve": {
            "alias": {
              "background-only$": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/background-only/error.js"
            }
          }
        },
        {
          "issuerLayer": "react:background",
          "resolve": {
            "alias": {
              "background-only$": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/background-only/empty.js"
            }
          }
        },
        {
          "test": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/background-only/error.js",
          "issuerLayer": "react:main-thread",
          "use": [
            {
              "loader": "/Users/bytedance/projects/rspeedy-minify-repro/node_modules/@lynx-js/react-rsbuild-plugin/dist/loaders/invalid-import-error-loader",
              "options": {
                "message": "'background-only' cannot be imported from a main-thread module."
              }
            }
          ]
        }
      ]
    },
    "optimization": {
      "minimize": false,
      "avoidEntryIife": true,
      "concatenateModules": false
    },
    "performance": {
      "hints": false
    },
    "entry": {
      "main__main-thread": {
        "layer": "react:main-thread",
        "import": [
          "./src/plain.js"
        ],
        "filename": "main__main-thread.js",
        "chunkLoading": false
      },
      "main": {
        "layer": "react:background",
        "import": [
          "./src/plain.js"
        ],
        "filename": "main.js",
        "chunkLoading": false
      }
    }
  }

config.output.path = process.env.OUT
  ? path.resolve(process.env.OUT)
  : config.output.path
config.plugins = [
  ...SOURCE_MAP_OPTIONS.map((options) => new rspack.SourceMapDevToolPlugin(options)),
  new Probe(),
]

export default config
